cabal-version: 3.0
name: crystal-parser
version: 0.1.0.0
author: Lautaro Bagnasco Muguillo
maintainer: tatibagnasco@gmail.com
build-type: Simple

common warnings
  ghc-options:
    -Wall
    -Wmissing-import-lists

library
  import: warnings
  exposed-modules:
    AstTypes
    Command.Parse
    Command.Rearrange
    OverloadingResolution.Detector
    PPrint
    Parser
    Rearranger
    TypeResolution.Fix
    TypeResolution.Resolver

  hs-source-dirs: src
  default-language: Haskell2010
  build-depends:
    base ^>=4.21.1.0,
    directory ^>=1.3.10,
    filepath ^>=1.5.5,
    hspec ^>=2.11.17,
    hspec-megaparsec ^>=2.2.1,
    megaparsec ^>=9.7,
    parser-combinators ^>=1.3,
    process ^>=1.6.28,
    string-interpolate ^>=0.3.4,
    text ^>=2.1.4,

executable crystal-parser
  import: warnings
  main-is: Main.hs
  other-modules:
    AstTypes
    Command.Parse
    Command.Rearrange
    OverloadingResolution.Detector
    PPrint
    Parser
    Rearranger
    TypeResolution.Fix
    TypeResolution.Resolver

  hs-source-dirs: src
  default-language: Haskell2010
  build-depends:
    base ^>=4.21.1.0,
    crystal-parser,
    directory ^>=1.3.10,
    filepath ^>=1.5.5,
    megaparsec ^>=9.7,
    process ^>=1.6.28,
    string-interpolate ^>=0.3.4,
    text ^>=2.1.4,

test-suite crystal-parser-test
  import: warnings
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  hs-source-dirs:
    test
    src

  default-language: Haskell2010
  other-modules:
    PPrint
    Parser
    Rearranger

  build-depends:
    base ^>=4.21.1.0,
    hspec ^>=2.11.17,
    hspec-megaparsec ^>=2.2.1,
    megaparsec ^>=9.7,
    string-interpolate ^>=0.3.4,
    text ^>=2.1.4,

  build-tool-depends:
    hspec-discover:hspec-discover ^>=2.11.17
